version: '3.7'

x-labels:
  labels: &default-label
    opencart:

services:
  db:
    image: mariadb
    labels: *default-label
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - opencart_db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - web
      - web-admin
      
  php:
    build: ./php
    labels: *default-label
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - opencart:/var/www/html
    depends_on:
      - db
      
    networks:
      - web
      - web-admin
      
  web:
    image: nginx:mainline-alpine
    labels: *default-label
    env_file:
      - .env
    environment:
      - LETSENCRYPT_HOST=${HOST}
      - VIRTUAL_HOST=${HOST}
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - opencart:/var/www/html
    restart: unless-stopped
    depends_on:
      - php
      - db
    networks:
      - proxy-tier
      - web
      
  web_admin:
    image: nginx:mainline-alpine
    labels: *default-label
    env_file:
      - .env
    environment:
      - LETSENCRYPT_HOST=${HOST_ADMIN}
      - VIRTUAL_HOST=${HOST_ADMIN}
    volumes:
      - ./nginx/default_admin.conf:/etc/nginx/conf.d/default.conf
      - opencart:/var/www/html
    restart: unless-stopped
    depends_on:
      - php
      - db
    networks:
      - proxy-tier
      - web-admin
      
  installation:
    build: ./installation
    env_file:
      - .env
    depends_on:
      - php
      - db
      - web
      - web_admin
    volumes:
      - opencart:/var/www/html
    networks:
      - web
      - web-admin

  jobber:
    build: ./jobber
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /backup:/backup
      - ./shellScript:/script:ro
    environment:
      - JOB_NAME1=Backup
      - JOB_COMMAND1=/bin/bash /script/backup.sh && /bin/bash /script/upload.sh
      - JOB_TIME1=0 0 20 * * 2 #Exec per Week at UTC Tue. 20
      - JOB_NOTIFY_ERR1=true
      - JOB_NOTIFY_FAIL1=true
    secrets:
      - rsyncpass
      
volumes:
  opencart:
    labels: *default-label
  opencart_db:
    labels: *default-label
  
networks:
  proxy-tier:
    external: true
    name: proxy-tier
  web:
  web-admin:
    
secrets:
  rsyncpass:
    file: ~/ssh.pas
